---
application:
  name: "twitter-export"
  project: "twitter-export"
  organization: "QoveryCommunity"
routers:
- name: "main-twitter-export"
  routes:
  - application_name: "twitter-export"
    paths:
    - "/*"
