version: '2'
services:
  mysql:
    container_name: ${APP_PREFIX}-mariadb
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_CRED}
      - MYSQL_USER=${MYSQL_CRED}
      - MYSQL_PASSWORD=${MYSQL_CRED}
      - MYSQL_DATABASE=${MYSQL_CRED}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_CRED}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/data/redis:/var/lib/redis:delegated
